Simple migration
RebelCode/rcmod-eddbk-cqrs pull request #3
Opened 2018-06-02 13:33 UTC by mecha

Resolves #2

2018-06-02 14:28 UTC, XedinUnknown requested changes

2018-06-02 14:28 UTC, XedinUnknown commented on config/config.php
> +    'cqrs' => [
If this is top-level configuration, then it needs to be contained under a node specific to the module.

2018-06-02 14:28 UTC, XedinUnknown commented on migrations/1/up.sql
> +create table if not exists ${table_prefix}session_rules
IMO the table names should come from config.

2018-06-02 14:28 UTC, XedinUnknown commented on src/EddBkCqrsModule.php
> +                    return new mysqli(DB_HOST, DB_USER, DB_PASSWORD, DB_NAME);
More coupling to environment, and even worse - to WP in particular. We should work out a way to remove usage of global constants from modules.

2018-06-02 14:51 UTC, mecha commented on src/EddBkCqrsModule.php
> +                    return new mysqli(DB_HOST, DB_USER, DB_PASSWORD, DB_NAME);
Agree. Any recommended alternative?

2018-06-02 16:16 UTC, mecha commented
Migrations have been [moved to a different module](https://github.com/RebelCode/rcmod-wp-bookings-cqrs/pull/3).

2018-06-04 17:25 UTC, mecha commented on config/config.php
> +    'cqrs' => [
Changing this will break the many things that depend on it. This should be done as a separate task and done carefully, across all concerned modules. There is a card on this [project](https://github.com/orgs/RebelCode/projects/2#card-10257746).

2018-06-05 08:42 UTC, XedinUnknown approved these changes

2018-06-05 08:42 UTC, merged